# Autogenerated wrapper script for QuantLibjl_jll for x86_64-linux-gnu
export libquantlibjl

using libjulia_jll
using libcxxwrap_julia_jll
using boost_jll
JLLWrappers.@generate_wrapper_header("QuantLibjl")
JLLWrappers.@declare_library_product(libquantlibjl, "libquantlibjl.so")
function __init__()
    JLLWrappers.@generate_init_header(libjulia_jll, libcxxwrap_julia_jll, boost_jll)
    JLLWrappers.@init_library_product(
        libquantlibjl,
        "lib/libquantlibjl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
